### ISSUE TITLE
无法找到ultraeval包

### ISSUE THREAD

**Issue by stepbystepcode** [OpenBMB/UltraEval#11]
## 问题描述
我通过mamba添加了一个名为llm的环境，并按照github的安装文档安装了依赖和环境，但是进行测评获取测评结果的时候提示ModuleNotFoundError: No module named 'ultraeval'，但是貌似已经正确安装了ultraeval包。
## 系统环境：
OS: Ubuntu 20.04.6 LTS x86_64 
Host: AS -4124GS-TNR 0123456789 
Kernel: 5.10.0-136.12.0.86.oe2203sp1.x86_64 
Shell: zsh 5.8 
Terminal: /dev/pts/6 
CPU: AMD EPYC 7763 (256) @ 2.450GHz 
GPU: NVIDIA A800 80GB PCIe*4
## 操作日志：
```
(base) ➜  UltraEval git:(main) ✗ mamba activate llm
(llm) ➜  UltraEval git:(main) ✗ which python3
/root/miniforge3/envs/llm/bin/python3
(llm) ➜  UltraEval git:(main) ✗ pip3 install .                                             
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Processing /root/UltraEval
  Preparing metadata (setup.py) ... done
Requirement already satisfied: vllm in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (0.3.2)
Requirement already satisfied: flask in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (3.0.2)
Requirement already satisfied: openai in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (1.12.0)
Requirement already satisfied: sacrebleu in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (2.4.0)
Requirement already satisfied: rouge_chinese in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (1.0.3)
Requirement already satisfied: pytablewriter in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (1.2.0)
Requirement already satisfied: gevent in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (24.2.1)
Requirement already satisfied: gunicorn in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (21.2.0)
Requirement already satisfied: tqdm in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (4.66.2)
Requirement already satisfied: pynvml in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (11.5.0)
Requirement already satisfied: accelerate>=0.20.3 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from UltraEval==0.1) (0.27.2)
Requirement already satisfied: numpy>=1.17 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from accelerate>=0.20.3->UltraEval==0.1) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from accelerate>=0.20.3->UltraEval==0.1) (23.2)
Requirement already satisfied: psutil in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from accelerate>=0.20.3->UltraEval==0.1) (5.9.8)
Requirement already satisfied: pyyaml in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from accelerate>=0.20.3->UltraEval==0.1) (6.0.1)
Requirement already satisfied: torch>=1.10.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from accelerate>=0.20.3->UltraEval==0.1) (2.1.2)
Requirement already satisfied: huggingface-hub in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from accelerate>=0.20.3->UltraEval==0.1) (0.20.3)
Requirement already satisfied: safetensors>=0.3.1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from accelerate>=0.20.3->UltraEval==0.1) (0.4.2)
Requirement already satisfied: Werkzeug>=3.0.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from flask->UltraEval==0.1) (3.0.1)
Requirement already satisfied: Jinja2>=3.1.2 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from flask->UltraEval==0.1) (3.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from flask->UltraEval==0.1) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from flask->UltraEval==0.1) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from flask->UltraEval==0.1) (1.7.0)
Requirement already satisfied: zope.event in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from gevent->UltraEval==0.1) (5.0)
Requirement already satisfied: zope.interface in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from gevent->UltraEval==0.1) (6.2)
Requirement already satisfied: greenlet>=2.0.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from gevent->UltraEval==0.1) (3.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from openai->UltraEval==0.1) (4.3.0)
Requirement already satisfied: distro<2,>=1.7.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from openai->UltraEval==0.1) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from openai->UltraEval==0.1) (0.27.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from openai->UltraEval==0.1) (2.6.1)
Requirement already satisfied: sniffio in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from openai->UltraEval==0.1) (1.3.0)
Requirement already satisfied: typing-extensions<5,>=4.7 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from openai->UltraEval==0.1) (4.9.0)
Requirement already satisfied: setuptools>=38.3.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from pytablewriter->UltraEval==0.1) (69.1.1)
Requirement already satisfied: DataProperty<2,>=1.0.1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from pytablewriter->UltraEval==0.1) (1.0.1)
Requirement already satisfied: mbstrdecoder<2,>=1.0.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from pytablewriter->UltraEval==0.1) (1.1.3)
Requirement already satisfied: pathvalidate<4,>=2.3.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from pytablewriter->UltraEval==0.1) (3.2.0)
Requirement already satisfied: tabledata<2,>=1.3.1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from pytablewriter->UltraEval==0.1) (1.3.3)
Requirement already satisfied: tcolorpy<1,>=0.0.5 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from pytablewriter->UltraEval==0.1) (0.1.4)
Requirement already satisfied: typepy<2,>=1.3.2 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->UltraEval==0.1) (1.3.2)
Requirement already satisfied: six in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from rouge_chinese->UltraEval==0.1) (1.16.0)
Requirement already satisfied: portalocker in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from sacrebleu->UltraEval==0.1) (2.8.2)
Requirement already satisfied: regex in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from sacrebleu->UltraEval==0.1) (2023.12.25)
Requirement already satisfied: tabulate>=0.8.9 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from sacrebleu->UltraEval==0.1) (0.9.0)
Requirement already satisfied: colorama in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from sacrebleu->UltraEval==0.1) (0.4.6)
Requirement already satisfied: lxml in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from sacrebleu->UltraEval==0.1) (5.1.0)
Requirement already satisfied: ninja in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (1.11.1.1)
Requirement already satisfied: ray>=2.9 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (2.9.3)
Requirement already satisfied: sentencepiece in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (0.2.0)
Requirement already satisfied: transformers>=4.38.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (4.38.1)
Requirement already satisfied: xformers==0.0.23.post1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (0.0.23.post1)
Requirement already satisfied: fastapi in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (0.109.2)
Requirement already satisfied: uvicorn[standard] in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (0.27.1)
Requirement already satisfied: aioprometheus[starlette] in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (23.12.0)
Requirement already satisfied: triton>=2.1.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (2.1.0)
Requirement already satisfied: cupy-cuda12x==12.1.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from vllm->UltraEval==0.1) (12.1.0)
Requirement already satisfied: fastrlock>=0.5 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from cupy-cuda12x==12.1.0->vllm->UltraEval==0.1) (0.8.2)
Requirement already satisfied: filelock in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (3.13.1)
Requirement already satisfied: sympy in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (1.12)
Requirement already satisfied: networkx in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (3.2.1)
Requirement already satisfied: fsspec in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.18.1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (2.18.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (12.1.105)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (12.3.101)
Requirement already satisfied: idna>=2.8 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from anyio<5,>=3.5.0->openai->UltraEval==0.1) (3.6)
Requirement already satisfied: exceptiongroup>=1.0.2 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from anyio<5,>=3.5.0->openai->UltraEval==0.1) (1.2.0)
Requirement already satisfied: certifi in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from httpx<1,>=0.23.0->openai->UltraEval==0.1) (2024.2.2)
Requirement already satisfied: httpcore==1.* in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from httpx<1,>=0.23.0->openai->UltraEval==0.1) (1.0.4)
Requirement already satisfied: h11<0.15,>=0.13 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai->UltraEval==0.1) (0.14.0)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from Jinja2>=3.1.2->flask->UltraEval==0.1) (2.1.5)
Requirement already satisfied: chardet<6,>=3.0.4 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from mbstrdecoder<2,>=1.0.0->pytablewriter->UltraEval==0.1) (5.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from pydantic<3,>=1.9.0->openai->UltraEval==0.1) (0.6.0)
Requirement already satisfied: pydantic-core==2.16.2 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from pydantic<3,>=1.9.0->openai->UltraEval==0.1) (2.16.2)
Requirement already satisfied: jsonschema in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from ray>=2.9->vllm->UltraEval==0.1) (4.21.1)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from ray>=2.9->vllm->UltraEval==0.1) (1.0.7)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from ray>=2.9->vllm->UltraEval==0.1) (4.25.3)
Requirement already satisfied: aiosignal in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from ray>=2.9->vllm->UltraEval==0.1) (1.3.1)
Requirement already satisfied: frozenlist in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from ray>=2.9->vllm->UltraEval==0.1) (1.4.1)
Requirement already satisfied: requests in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from ray>=2.9->vllm->UltraEval==0.1) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from transformers>=4.38.0->vllm->UltraEval==0.1) (0.15.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->UltraEval==0.1) (2.8.2)
Requirement already satisfied: pytz>=2018.9 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from typepy[datetime]<2,>=1.3.2->pytablewriter->UltraEval==0.1) (2024.1)
Requirement already satisfied: orjson in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from aioprometheus[starlette]->vllm->UltraEval==0.1) (3.9.15)
Requirement already satisfied: quantile-python>=1.1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from aioprometheus[starlette]->vllm->UltraEval==0.1) (1.1)
Requirement already satisfied: starlette>=0.14.2 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from aioprometheus[starlette]->vllm->UltraEval==0.1) (0.36.3)
Requirement already satisfied: httptools>=0.5.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from uvicorn[standard]->vllm->UltraEval==0.1) (0.6.1)
Requirement already satisfied: python-dotenv>=0.13 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from uvicorn[standard]->vllm->UltraEval==0.1) (1.0.1)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from uvicorn[standard]->vllm->UltraEval==0.1) (0.19.0)
Requirement already satisfied: watchfiles>=0.13 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from uvicorn[standard]->vllm->UltraEval==0.1) (0.21.0)
Requirement already satisfied: websockets>=10.4 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from uvicorn[standard]->vllm->UltraEval==0.1) (12.0)
Requirement already satisfied: attrs>=22.2.0 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from jsonschema->ray>=2.9->vllm->UltraEval==0.1) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from jsonschema->ray>=2.9->vllm->UltraEval==0.1) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from jsonschema->ray>=2.9->vllm->UltraEval==0.1) (0.33.0)
Requirement already satisfied: rpds-py>=0.7.1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from jsonschema->ray>=2.9->vllm->UltraEval==0.1) (0.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from requests->ray>=2.9->vllm->UltraEval==0.1) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from requests->ray>=2.9->vllm->UltraEval==0.1) (2.2.1)
Requirement already satisfied: mpmath>=0.19 in /root/miniforge3/envs/llm/lib/python3.10/site-packages (from sympy->torch>=1.10.0->accelerate>=0.20.3->UltraEval==0.1) (1.3.0)
Building wheels for collected packages: UltraEval
  Building wheel for UltraEval (setup.py) ... done
  Created wheel for UltraEval: filename=UltraEval-0.1-py3-none-any.whl size=32172 sha256=e8154b5db7531a5414a5492d97d2e6feb8c8f4cb3f7b0385c1122439e07ff4ef
  Stored in directory: /tmp/pip-ephem-wheel-cache-swap1pul/wheels/8f/d9/09/74a86c8421559fc67c738989dbd45bfae23fe412be5eca8747
Successfully built UltraEval
Installing collected packages: UltraEval
  Attempting uninstall: UltraEval
    Found existing installation: UltraEval 0.1
    Uninstalling UltraEval-0.1:
      Successfully uninstalled UltraEval-0.1
Successfully installed UltraEval-0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(llm) ➜  UltraEval git:(main) ✗ pip3 show ultraeval   
Name: UltraEval
Version: 0.1
Summary: An open source framework for evaluating foundation models
Home-page: 
Author: UltraEval Team
Author-email: 
License: 
Location: /root/miniforge3/envs/llm/lib/python3.10/site-packages
Requires: accelerate, flask, gevent, gunicorn, openai, pynvml, pytablewriter, rouge-chinese, sacrebleu, tqdm, vllm
Required-by: 
(llm) ➜  UltraEval git:(main) ✗ python3 main.py \    
    --model general \
    --model_args url="http://127.0.0.1:5002",concurrency=1 \
    --config_path configs/eval_config.json \
    --output_base_path logs \
    --batch_size 1 \
    --postprocess general_torch \
    --params models/model_params/vllm_sample.json \
    --write_out
Traceback (most recent call last):
  File "/root/UltraEval/main.py", line 219, in <module>
    main()
  File "/root/UltraEval/main.py", line 203, in main
    evaluator = Evaluator(args)
  File "/root/UltraEval/main.py", line 43, in __init__
    self.build_tasks(data_config)
  File "/root/UltraEval/main.py", line 70, in build_tasks
    eval_task.EvalTask(
  File "/root/UltraEval/tasks/eval_task.py", line 46, in __init__
    self._transform_func = utils.import_function_from_path(
  File "/root/UltraEval/utils/utils.py", line 43, in import_function_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/UltraEval/datasets/bbh-cot/transform_gen_cot.py", line 3, in <module>
    from ultraeval.tasks.postprocess import ExactMatchPost
ModuleNotFoundError: No module named 'ultraeval'
```

**Comment by Hothan01** [comment]
Bug已经修复了，可以拉取下最新代码
